version: '3.7'

services:
  minio:
    image: minio/minio:latest
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  db:
    image: postgres:12.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
